"""Write the prompt assets the ADK agent needs. Deploy-ready, not deployed.

The ADK package (deploy/gcp/tariff_adk) runs in its own environment (deploy/gcp/.venv)
without the tariffagent package, so it cannot import the prompts. This script runs in
the project environment and exports them to deploy/gcp/tariff_adk/_assets.json:
role texts of the multi-agent team (tariffagent.agents.multi), the skill body, the GRI
text from the database, the JSON schemas and the Vertex model ids. One source of truth,
no copies of prompt text in the deploy package.

    DATA_DIR=deploy/.build/agent_data uv run python deploy/gcp/build_assets.py
"""

from __future__ import annotations

import hashlib
import json
from pathlib import Path

OUT = Path(__file__).resolve().parent / "tariff_adk" / "_assets.json"


def main() -> int:
    from tariffagent.agents import multi
    from tariffagent.agents.schemas import ADVOCATE_SCHEMA, CLASSIFICATION_SCHEMA, PLAN_SCHEMA
    from tariffagent.agents.single import system_blocks
    from tariffagent.config import get_settings
    from tariffagent.llm.cloud import VERTEX_MODEL_IDS

    blocks = system_blocks()
    skill, gri = blocks[1]["text"], blocks[2]["text"]
    if "<general_rules_of_interpretation" not in gri or len(gri) < 1000:
        raise SystemExit("GRI text missing from the database at DATA_DIR")
    s = get_settings()
    assets = {
        "note": "Generated by deploy/gcp/build_assets.py from the tariffagent package. Do not edit.",
        "skill_block": skill,
        "gri_block": gri,
        "orchestrator_role": multi.ORCH_ROLE,
        "advocate_role": multi.ADVOCATE_ROLE,
        "adjudicator_role": multi.ADJ_ROLE,
        "orchestrator_tools": sorted(multi.ORCH_TOOLS),
        "advocate_tools": sorted(multi.ADV_TOOLS),
        "adjudicator_tools": sorted(multi.ADJ_TOOLS),
        "plan_schema": PLAN_SCHEMA,
        "advocate_schema": ADVOCATE_SCHEMA,
        "classification_schema": CLASSIFICATION_SCHEMA,
        "models": {"advocate": s.advocate_model, "reasoner": s.reasoner_model},
        "vertex_model_ids": VERTEX_MODEL_IDS,
    }
    blob = json.dumps(assets, indent=1, ensure_ascii=False)
    assets["sha256"] = hashlib.sha256(blob.encode()).hexdigest()
    OUT.write_text(json.dumps(assets, indent=1, ensure_ascii=False))
    print(f"wrote {OUT} ({OUT.stat().st_size / 1000:.0f} kB, sha256 {assets['sha256'][:12]})")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
